# Generated by Django 5.0.2 on 2024-02-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Корзина пользователя',
                'verbose_name_plural': 'Корзины пользователей',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование категории')),
                ('slug_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='SLUG')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='Изображение категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование продукта')),
                ('slug_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='SLUG')),
                ('image_small', models.ImageField(upload_to='product_images/small/', verbose_name='Изображение продукта(маленькое)')),
                ('image_medium', models.ImageField(upload_to='product_images/meduim/', verbose_name='Изображение продукта(среднее)')),
                ('image_large', models.ImageField(upload_to='product_images/large/', verbose_name='Изображение продукта(большое)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование подкатегории')),
                ('slug_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='SLUG')),
                ('image', models.ImageField(upload_to='subcategory_images/', verbose_name='Изображение подкатегории')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
    ]
