# Generated by Django 5.0.2 on 2024-02-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/large/', verbose_name='Изображение продукта(большое)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/meduim/', verbose_name='Изображение продукта(среднее)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/small/', verbose_name='Изображение продукта(маленькое)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_images/', verbose_name='Изображение подкатегории'),
        ),
    ]
